name: Dependency Updates

on:
  schedule:
    # Run weekly on Mondays at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:

env:
  NODE_VERSION: '18'

jobs:
  update-dependencies:
    name: Update Dependencies
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Configure Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

    - name: Update backend dependencies
      run: |
        npm update
        npm audit fix --audit-level moderate || true

    - name: Update frontend dependencies
      run: |
        cd frontend
        npm update
        npm audit fix --audit-level moderate || true

    - name: Update CDK dependencies
      run: |
        npm install aws-cdk@latest aws-cdk-lib@latest
        cd frontend && npm install @aws-amplify/ui-react@latest aws-amplify@latest

    - name: Run tests after updates
      run: |
        npm test -- --watchAll=false
        cd frontend && npm test -- --watchAll=false

    - name: Check for changes
      id: changes
      run: |
        if git diff --quiet; then
          echo "changes=false" >> $GITHUB_OUTPUT
        else
          echo "changes=true" >> $GITHUB_OUTPUT
        fi

    - name: Create Pull Request
      if: steps.changes.outputs.changes == 'true'
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore: update dependencies'
        title: 'chore: automated dependency updates'
        body: |
          ## Automated Dependency Updates
          
          This PR contains automated dependency updates performed by GitHub Actions.
          
          ### Changes
          - Updated npm dependencies to latest compatible versions
          - Applied security fixes where available
          - Updated AWS CDK and Amplify dependencies
          
          ### Testing
          - [x] Backend tests pass
          - [x] Frontend tests pass
          - [ ] Manual testing required
          
          ### Review Checklist
          - [ ] Review dependency changes
          - [ ] Check for breaking changes
          - [ ] Verify security updates
          - [ ] Test in development environment
          
          **Note:** This PR was created automatically. Please review carefully before merging.
        branch: automated/dependency-updates
        delete-branch: true
        labels: |
          dependencies
          automated
          maintenance

  security-updates:
    name: Security Updates
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Configure Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

    - name: Apply security updates
      run: |
        npm audit fix --force || true
        cd frontend && npm audit fix --force || true

    - name: Run security scan
      run: |
        npm audit --audit-level high || true
        cd frontend && npm audit --audit-level high || true

    - name: Check for changes
      id: security-changes
      run: |
        if git diff --quiet; then
          echo "changes=false" >> $GITHUB_OUTPUT
        else
          echo "changes=true" >> $GITHUB_OUTPUT
        fi

    - name: Create Security Update PR
      if: steps.security-changes.outputs.changes == 'true'
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'security: apply automated security updates'
        title: 'security: automated security updates'
        body: |
          ## Automated Security Updates
          
          This PR contains automated security updates performed by GitHub Actions.
          
          ### Security Fixes Applied
          - Applied npm audit fixes for high and critical vulnerabilities
          - Updated vulnerable dependencies to secure versions
          
          ### Priority
          **HIGH** - This PR contains security fixes and should be reviewed and merged promptly.
          
          ### Testing Required
          - [ ] Run full test suite
          - [ ] Deploy to development environment
          - [ ] Verify application functionality
          - [ ] Run security scan to confirm fixes
          
          **Note:** This PR was created automatically due to security vulnerabilities.
        branch: automated/security-updates
        delete-branch: true
        labels: |
          security
          automated
          high-priority